# Generated by Django 5.2 on 2025-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_savedtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtrip',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
