# Generated by Django 5.2 on 2025-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_savedtrip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtrip',
            name='destination_image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
