# Generated by Django 5.2 on 2025-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activitynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynote',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
