version: "3.9"

services: 
  redis:
    image: redis
    container_name: redis 
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres:14
    container_name: trip_planner_local_db
    restart: always 
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    container_name: trip-backend 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app 
    env_file:
      - ./backend/.env 

    depends_on:
      - redis
      - db

    command: sh -c "python manage.py migrate --noinput && exec gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  frontend: 
    build: ./frontend
    container_name: trip-frontend 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
      - /app/.next       
    environment:
      PORT: 3000 

    depends_on:
      - backend

volumes:
  postgres_local_data:
  redis-data: