import './globals.css';
import Header from '@/components/ui/header';
import Footer from './components/Footer/Footer';
import { AuthProvider } from './(auth)/context/AuthContext'; // Assuming this is the correct path


export const metadata = {
  title: 'dSign',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" /> 
      <link href="https://fonts.googleapis.com/css2?family=Gloock&display=swap" rel="stylesheet" />
    </head>
      <body>
        <AuthProvider>
          <Header />
        {children}
        <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
